require "plugins.impatient" -- This should be at the top of the list as it is needed for the plugin.
require "core.options"
require "core.keymaps"
require "packer_init"
--require "personal.autocommands"
require "core.colorscheme"
require "plugins.nvim-cmp"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.gitsigns"
require "plugins.nvim-tree"
require "plugins.bufferline"
require "plugins.toggleterm"
require "plugins.tabnine"
require "plugins.lualine"
require "plugins.whichkey"
require "plugins.project"
require "plugins.indentline"
require "plugins.todo-comments"
-- require "plugins.null-ls"
require "plugins.dap-ui"
require "lsp" -- Can require directories without the specific name of file. Just include an init.lua file within the directory
--require "personal.dap"
